ARG BASE=quay.io/fedora/fedora-bootc:42

FROM ${BASE}

RUN mkdir -p /var/roothome

RUN dnf install -y \
    @core \    
    podman \
    jq curl wget rsync bash-completion \
    && dnf clean all && rm -rf /var/cache/libdnf5
    

RUN systemctl enable --now podman
RUN systemctl disable --now firewalld
